### ISSUE TITLE
Harden your GitHub account

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-gaupt#1]
Enable 2FA:
* [x] proceed at https://github.com/settings/security
* [x] I recommend using the following OTP code generator: https://play.google.com/store/apps/details?id=org.liberty.android.freeotpplus&hl=en_US

**Comment by gaupt** [comment]
Do you meane to create 2 Factor identification my account and GitHub?

**Comment by webknjaz** [comment]
I mean you should configure 2FA in GH via an authenticator app.

**Comment by gaupt** [comment]
Create identification by Authy
