### ISSUE TITLE
Create an SSH key and add it to GitHub account

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-gaupt#3]
See:
* https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#generating-a-new-ssh-key (you may omit adding a password)
* https://help.github.com/articles/connecting-to-github-with-ssh/

After completing instructions, post the result of the following command in a comment to this issue:
```shell
ssh -T git@github.com
```

Check yourself
--------------

If performed correctly, you'll see your GitHub username in the console output.

**Comment by gaupt** [comment]
Hi! I have a little problem with ssh connect to Github:
"Hi gaupt! You've successfully authenticated, but GitHub does not provide shell access."

**Comment by webknjaz** [comment]
It's not a problem. This is an expected outcome that proves that your SSH setup is correct.

You solved your first task! Congrats! :confetti_ball:
